spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/todo_db?serverTimezone=Asia/Seoul
    username: #db_user
    password: #db_pasword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create

  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

server:
  error:
    whitelabel:
      enabled: false
